name: Export-ManiFest CICD
env:
  repo: workato-cicd
  owner: rajeshjanapati
  DEPLOYMENT_NAME: Export-ManiFest CICD
  manifest_id: ${{ github.event.inputs.manifest_Id }}
  Workato_Token: ${{ secrets.WORKATOTOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

on:
  repository_dispatch:
    types: [workato]
    inputs:
      manifest_Id:
        type: string
        required: true
        description: Recipe manifest Id to Export
        default: "101814"
        options:
          - "101814"

jobs:
  Workato-CICD:
    name: Export-ManiFest CICD
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Set TIMESTAMP
        id: set_timestamp
        run: |
          echo "TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S %Z")" >> $GITHUB_ENV
