name: Export-ManiFest CICD
on:
  repository_dispatch:
    types: [Export-cicd]
    inputs:
      manifest_Id:
        type: string
        required: true
        description: Recipe manifest Id to Export
        default: "101814"
        options:
          - "101814"

jobs:
  Workato-CICD:
    runs-on: ubuntu-latest

    steps:
      - name: Set Manifest ID
        run: echo "Manifest ID: ${{ github.event.inputs.manifest_Id }}"
