name: Export-ManiFest CICD

on:
  repository_dispatch:
    types: [workato]

jobs:
  Workato-CICD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
          
      - name: Set TIMESTAMP
        id: set_timestamp
        run: |
          echo "TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S %Z")" >> $GITHUB_ENV

      # Add more steps as needed
