name: Export-ManiFest CICD

on:
  workflow_dispatch:
    inputs:
      manifest_Id:
        description: 'Recipe manifest Id to Export'
        required: true
        default: '101814'

jobs:
  Workato-CICD:
    runs-on: ubuntu-latest

    steps:
      - name: Set Manifest ID
        run: echo "Manifest ID: ${{ github.event.inputs.manifest_Id }}"
