name: Import-ManiFest CICD
on:
  workflow_dispatch:
    inputs:
      folder-Id:
        type: string
        required: true
        description: Recipe folder Id to Import
      manifest-name:
        type: string
        required: true
        description: Manifest Name to Import
env:
  DEPLOYMENT_NAME: Import-ManiFest CICD
  folder_Id: ${{ github.event.inputs.folder-Id }}
  manifest_name: ${{ github.event.inputs.manifest-name }}
  Workato_Token: ${{ secrets.PRODACCESSTOKEN }}

jobs:
  Workato-CICD:
    name: Import-ManiFest CICD
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Export CICD
      shell: pwsh
      run: |
        $env:access_token = "${{ secrets.PRODACCESSTOKEN }}"
        $env:folder_Id = ${{env.folder_Id}}
        $env:manifest_name = ${env.manifest_name}}
        Invoke-Pester ./import.ps1 -Passthru
        # ./import.ps1 -accessToken "${{ secrets.PRODACCESSTOKEN }}" -manifestName ${{env.manifest_name}} -folderId ${{env.folder_Id}}
