name: Import-ManiFest CICD
on:
  workflow_dispatch:
    inputs:
      folder_Id:
        type: string
        required: true
        description: Recipe folder Id to Import
      manifest_Name:
        type: string
        required: true
        description: Manifest Name to Import
        
        
env:
  DEPLOYMENT_NAME: Import-ManiFest CICD
  folder_Id: ${{ github.event.inputs.folder_Id }}
  manifest_name: ${{ github.event.inputs.manifest_name }}
  Workato_Token: ${{ secrets.PRODACCESSTOKEN }}

jobs:
  Workato-CICD:
    name: Import-ManiFest CICD
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out Git repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUBTOKEN }}"
          
      - name: Import CICD
        shell: pwsh
        run: |
          ./import.ps1 -accessToken "${{ secrets.PRODACCESSTOKEN }}" -manifestName ${{env.manifest_name}} -folderId ${{env.folder_Id}}

