name: Workato-CICD
on:
  push:
    branches:
      - main  # Adjust this to your main branch name

env:
  DEPLOYMENT_NAME: CICD Push
  Workato_Token: ${{ secrets.WORKATOTOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  Workato-CICD:
    name: Workato-CICD
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out Git repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUBTOKEN }}"

      - name: CICD
        shell: pwsh
        run: |
          $env:github_token = "${{ secrets.GITHUBTOKEN }}"
          $env:access_token = "${{ secrets.WORKATOTOKEN }}"
          Invoke-Pester ./scripts.ps1 -Passthru

      - name: Create cicd branch if not exists
        run: |
          git show-ref --verify --quiet refs/heads/cicd || git checkout -b cicd

      - name: Add local files to Git local branch
        run: |
          git config --global user.email "rajeshjanapati@gmail.com"
          git config --global user.name "rajeshjanapati"
          git add .

      - name: Check for changes
        id: check_git_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected, pulling latest changes..."
            git config pull.rebase true  # Set pull.rebase to true
            git pull origin cicd
            git add .
            git commit -m "cicd update"
          else
            echo "No changes to commit."
            exit 0
          fi

      - name: Push changes to Git
        run: |
          git push origin cicd

